language: cpp
dist: focal
cache:
  ccache: true
  directories:
  - /home/travis/_install
os: linux

addons:
  apt:
    packages: &base_packages
      - libblas-dev
      - liblapack-dev
      - liblapacke-dev
      - libtbb-dev
      - cmake
      - cmake-data
      - flex
      - ninja-build

env:
  global:
    - BUILD_PREFIX=/home/travis/_build
    - INSTALL_PREFIX=/home/travis/_install

matrix:
  fast_finish: true
  include:
    - compiler: gcc
      env: GCC_VERSION=8 BUILD_TYPE=Debug COMPUTE_COVERAGE=1
      addons:
        apt:
          sources:
            - *base_sources
          packages:
            - *base_packages
            - g++-8
            - lcov
    - compiler: gcc
      env: GCC_VERSION=8 BUILD_TYPE=Release
      addons:
        apt:
          sources:
            - *base_sources
          packages:
            - *base_packages
            - g++-8
    - compiler: gcc
      env: GCC_VERSION=9 BUILD_TYPE=Debug
      addons:
        apt:
          sources:
            - sourceline: 'ppa:ubuntu-toolchain-r/test'
          packages:
            - *base_packages
            - g++-9
            - gfortran-9
    - compiler: gcc
      env: GCC_VERSION=9 BUILD_TYPE=Release
      addons:
        apt:
          sources:
            - sourceline: 'ppa:ubuntu-toolchain-r/test'
          packages:
            - *base_packages
            - g++-9
            - gfortran-9
    - compiler: clang
      env: CLANG_VERSION=7 GCC_VERSION=8 BUILD_TYPE=Debug
      addons:
        apt:
          sources:
            - *base_sources
            - *clang7_sources
          packages:
            - *base_packages
            - clang-7
            - libc++-7-dev
            - libc++abi-7-dev
            - g++-8
    - compiler: clang
      env: CLANG_VERSION=7 GCC_VERSION=8 BUILD_TYPE=Release
      addons:
        apt:
          sources:
            - *base_sources
            - *clang7_sources
          packages:
            - *base_packages
            - clang-7
            - libc++-7-dev
            - libc++abi-7-dev
            - g++-8
    - compiler: clang
      env: CLANG_VERSION=8 GCC_VERSION=8 BUILD_TYPE=Debug
      addons:
        apt:
          sources:
            - *base_sources
            - *clang8_sources
          packages:
            - *base_packages
            - clang-8
            - libc++-8-dev
            - libc++abi-8-dev
            - g++-8
    - compiler: clang
      env: CLANG_VERSION=8 GCC_VERSION=8 BUILD_TYPE=Release
      addons:
        apt:
          sources:
            - *base_sources
            - *clang8_sources
          packages:
            - *base_packages
            - clang-8
            - libc++-8-dev
            - libc++abi-8-dev
            - g++-8
    - compiler: clang
      env: CLANG_VERSION=9 GCC_VERSION=8 BUILD_TYPE=Debug
      addons:
        apt:
          sources:
            - sourceline: 'deb http://apt.llvm.org/focal/ llvm-toolchain-focal main'
              key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
          packages:
            - *base_packages
            - g++-8
            - gfortran-8
            - clang-9
            - libc++-9-dev
            - libc++abi-9-dev
    - compiler: clang
      env: CLANG_VERSION=9 GCC_VERSION=8 BUILD_TYPE=Release DEPLOY=1
      addons:
        apt:
          sources:
            - sourceline: 'deb http://apt.llvm.org/focal/ llvm-toolchain-focal main'
              key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
          packages:
            - *base_packages
            - g++-8
            - gfortran-8
            - clang-9
            - libc++-9-dev
            - libc++abi-9-dev
            - libclang1-9 # needed to run doxygen
            - graphviz # provides dot for doxygen graphs
            - fonts-liberation # recommended by graphviz

before_install:
- "env"
- "mkdir -p ${BUILD_PREFIX} && mkdir -p ${INSTALL_PREFIX}"

script:
  - ${TRAVIS_BUILD_DIR}/bin/build-$TRAVIS_OS_NAME.sh

after_failure:
- cat ${BUILD_PREFIX}/ttg/CMakeFiles/CMakeOutput.log
- cat ${BUILD_PREFIX}/ttg/CMakeFiles/CMakeError.log

# codecov
after_success:
  # create report
  - cd ${TRAVIS_BUILD_DIR}
  - if [ "$COMPUTE_COVERAGE" = "1" ]; then lcov --gcov-tool gcov-${GCC_VERSION} --directory ${BUILD_PREFIX}/ttg --capture --output-file coverage.info; fi; # capture coverage info
  - if [ "$COMPUTE_COVERAGE" = "1" ]; then lcov --remove coverage.info '/usr/*' '*/eigen3/*' '*/BTAS/*' '*/boost/*' '*/tests/*' '*/examples/*' --output-file coverage.info; fi; # filter out non-project files
  - if [ "$COMPUTE_COVERAGE" = "1" ]; then lcov --list coverage.info; fi; #debug info
  # upload report to CodeCov
  #- if [ "$COMPUTE_COVERAGE" = "1" ]; then bash <(curl -s https://codecov.io/bash) -t c0d0a777-cce2-48fa-8ec0-863ce1dcf446; fi;
  # generate docs for the master only
  - if [ "$DEPLOY" = "1" ] && [ "$TRAVIS_PULL_REQUEST" = "false" ] && [ "$TRAVIS_BRANCH" = "master" ]; then bash ${TRAVIS_BUILD_DIR}/bin/deploy-$TRAVIS_OS_NAME.sh; fi;

notifications:
  slack:
    secure: aTBPnV/QUvD5zjB82Gz8MwqtjDcxMuAtGY3m2KM4kD54kxZxPXGC7sHb9e/EOHm0qoudTR8aielY99y9mPH3v/5qXvyQKU3md+aE9i+XB2ewm5WXDUXmr8wS63W+9EflXfFeC1JxantyYkZ9n4itCZP7WlY9x7rMfs/+1P5A0Ew=
