language: cpp
dist: bionic
cache:
  ccache: true
  directories:
  - /home/travis/_install
os: linux

addons:
  apt:
    sources: &base_sources
      - ubuntu-toolchain-r-test
    sources: &clang7_sources
      - llvm-toolchain-bionic-7
    sources: &clang8_sources
      - llvm-toolchain-bionic-8
    packages: &base_packages
      - libblas-dev
      - liblapack-dev
      - libtbb-dev
      - cmake
      - cmake-data
      - lcov

env:
  global:
    - BUILD_PREFIX=/home/travis/_build
    - INSTALL_PREFIX=/home/travis/_install
    - secure: "ViPuTudbp6uEkL7OlDZchqRn9YxjDJo/esEdvcKCf+1gBzvBEhxRMGkW39loMlXpnUm3hRAmebOLbP7ceP1pd0AY/eMM93K7JuJBZvld2n70ChCKXFJL+GTzAxRQJ/bJTks6RrEGbmGWNl8aAXfYsqoMgcNoFgjtLJoXQv9aZJmX4lM3VjzTBadAdwRR/qCiFUg1pHkr+dg1aRAuvBQ6s0q56ApM6MLYtFDGobV+bkKwfY3XTKzNjEtyGZ0lTa8MgDT43KEHKl8XNC59rbIOnTQF+wqzPQmdqKpYy3D15CHOoIUEIZ1R6L3OXTbYZD0r6lG7j2udjGo7zfRw9T9h4gQrdDwbAjeZeXHiCdWiLvfbISBfJqmffp4DaONV6dhvPT8KEEc/fGErTCH4Lv4AjJu/F/qaYzWMIE3FVl9J5D94ze7OJ6MHCzRsJp12zb7o/yCXc9/4mBQt0ITJ/bBRFaiwPrYN74U43Cw36ZuX2iTT2b2NkBTy9X3qrW7chVBmlmrDCMuRPRIBLTVtDUoakAHdH/1D+UkLPY5XHUimrzsJ1lWNb/d3N3XzJum5n0yv8G0chBPsipzl/XBEnHKbIduOjxYy0gp5kCuLcrj0EoPNx+E4j6XcZnFIn27rlaTUplWBZ48I9SJK7HYPkNBGHu/jUzqYdde1lhGiJrpMahQ="

branches:
  only:
  - master

matrix:
  fast_finish: true
  include:
    - compiler: gcc
      env: GCC_VERSION=8 BUILD_TYPE=Debug
      addons:
        apt:
          sources:
            - *base_sources
          packages:
            - *base_packages
            - g++-8
    - compiler: gcc
      env: GCC_VERSION=8 BUILD_TYPE=Release
      addons:
        apt:
          sources:
            - *base_sources
          packages:
            - *base_packages
            - g++-8
    - compiler: clang
      env: CLANG_VERSION=7 GCC_VERSION=8 BUILD_TYPE=Debug
      addons:
        apt:
          sources:
            - *base_sources
            - *clang7_sources
          packages:
            - *base_packages
            - clang-7
            - libc++-7-dev
            - libc++abi-7-dev
            - g++-8
    - compiler: clang
      env: CLANG_VERSION=7 GCC_VERSION=8 BUILD_TYPE=Release
      addons:
        apt:
          sources:
            - *base_sources
            - *clang7_sources
          packages:
            - *base_packages
            - clang-7
            - libc++-7-dev
            - libc++abi-7-dev
            - g++-8
    - compiler: clang
      env: CLANG_VERSION=8 GCC_VERSION=8 BUILD_TYPE=Debug
      addons:
        apt:
          sources:
            - *base_sources
            - *clang8_sources
          packages:
            - *base_packages
            - clang-8
            - libc++-8-dev
            - libc++abi-8-dev
            - g++-8
    - compiler: clang
      env: CLANG_VERSION=8 GCC_VERSION=8 BUILD_TYPE=Release
      addons:
        apt:
          sources:
            - *base_sources
            - *clang8_sources
          packages:
            - *base_packages
            - clang-8
            - libc++-8-dev
            - libc++abi-8-dev
            - g++-8
            - doxygen  # gcc8 Release build deploys dox
            - graphviz # provides dot for doxygen graphs
            - fonts-liberation # recommended by graphviz

before_install:
- "env"
- "mkdir -p ${BUILD_PREFIX} && mkdir -p ${INSTALL_PREFIX}"

script:
  - ./bin/build-$TRAVIS_OS_NAME.sh

after_failure:
- cat ${BUILD_PREFIX}/ttg/CMakeFiles/CMakeOutput.log
- cat ${BUILD_PREFIX}/ttg/CMakeFiles/CMakeError.log

# codecov
after_success:
  # create report
  - cd ${TRAVIS_BUILD_DIR}
  - if [ "$BUILD_TYPE" = "Debug" ] && [ "$GCC_VERSION" = 8 ]; then lcov --gcov-tool gcov-${GCC_VERSION} --directory ${BUILD_PREFIX}/ttg --capture --output-file coverage.info; fi; # capture coverage info
  - if [ "$BUILD_TYPE" = "Debug" ] && [ "$GCC_VERSION" = 8 ]; then lcov --remove coverage.info '/usr/*' '*/eigen3/*' '*/BTAS/*' '*/boost/*' '*/tests/*' '*/examples/*' --output-file coverage.info; fi; # filter out non-project files
  - if [ "$BUILD_TYPE" = "Debug" ] && [ "$GCC_VERSION" = 8 ]; then lcov --list coverage.info; fi; #debug info
  # upload report to CodeCov
  #- if [ "$BUILD_TYPE" = "Debug" ] && [ "$GCC_VERSION" = 8 ]; then bash <(curl -s https://codecov.io/bash) -t c0d0a777-cce2-48fa-8ec0-863ce1dcf446; fi;
  # generate docs
  - if [ "$BUILD_TYPE" = "Release" ] && [ "$CLANG_VERSION" = 8 ]; then bash ./bin/deploy-$TRAVIS_OS_NAME.sh; fi;

notifications:
  slack:
    secure: aTBPnV/QUvD5zjB82Gz8MwqtjDcxMuAtGY3m2KM4kD54kxZxPXGC7sHb9e/EOHm0qoudTR8aielY99y9mPH3v/5qXvyQKU3md+aE9i+XB2ewm5WXDUXmr8wS63W+9EflXfFeC1JxantyYkZ9n4itCZP7WlY9x7rMfs/+1P5A0Ew=
